version: "3.8"
services:
        backend:
          build: .
          image: backend:production
          environment:
            - DB_HOST=${DB_HOST}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - CROSS_ORIGIN=${CROSS_ORIGIN}
          volumes:
            - ~/backend_data:/assets/pictures
networks:
    default:
        external:
            name: integrated-network
